# Generated by Django 5.1.5 on 2025-01-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="target_days_per_week",
            field=models.IntegerField(default=7),
        ),
    ]
